name: rdfgraph
description:
  A dart toolkit for organizing RDF files inspired by RDFLib.
  Current functinalities include creating a graph to store different triples,
  finding subjects/objects based on specified criteria, exporting to turtle file, etc.
version: 0.0.6
homepage: https://github.com/tian3rd/rdfgraph.git

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  logging: ^1.0.2

dev_dependencies:
